name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Install Playwright
        run: yarn playwright install --with-deps
      - name: Test
        run: yarn start-server-and-test preview http://localhost:3000 test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Percy
        run: npx @percy/cli upload e2e/screenshots/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
