name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  id-token: write
jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true
          run-install: false
      - name: Install dependencies
        run: vp install
      - name: Check
        run: vp check
      - name: Build
        run: vp build
      - name: Install Playwright
        uses: dtinth/setup-playwright-test-docker@main
      - name: JavaScript tests
        run: vp test
      - name: End-to-end tests
        run: vp run test
      - name: Publish storyboard
        run: vp dlx 'github:dtinth/publish-storyboard#main' --input=test-storyboards
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Percy
        run: vp dlx @percy/cli upload e2e/screenshots/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
